### PR TITLE
Nimbus patch 1

### PR DESCRIPTION
**Pull request by swarnim1212**
added images dirr and background image in jumbotron section
here is the screen shot:
image

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@nimbus1212  let's wait for other reviewers to review.

**Review by divyanshu-rawat — APPROVED** [review]
PR and written code looks good but it would be great If you can show us live what you have done like deploying what you have done to github pages anyways nimbus thanks for the PR.

**Review by punit-agarwal — APPROVED** [review]

**Review by punit-agarwal — APPROVED** [review]

**Comment by yashovardhan** [comment]
Looks good.. would have provided a live version to review... 
although just my personal point it maybe
I preferred a simple minimalistic design with no images as in the background.

Let others the comment or approve.

A great work it was anyway!

**Comment by sid22** [comment]
Yes @nimbus1212, I too would like the site to be free of images as of now.

**Comment by yashovardhan** [comment]
@nimbus1212 do you anything else in your mind regarding this PR?
if not then you may close this for now :)

**Comment by swarnim1212** [comment]
Yes I am closing it for now @goyal-sidd also want no images as of now

**Pull request closed without merging**
