### PR TITLE
M1 End sem 17-18 Question Paper

### PR DESCRIPTION
**Pull request by Naman-Garg-06**
Fixes #

#### Checklist

- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)

**Changes proposed in this pull request**
-
-
-

**Screenshots (if appropriate)** 

**Link to live demo (if appropriate):** 

**Closes #**

### CODE REVIEW

**Review by punit-agarwal — APPROVED** [review]

**Review by yashovardhan — CHANGES_REQUESTED** [review]
rename the file and put it in all the subject folders

**Comment by yashovardhan** [comment]
unack https://github.com/Cybros-LNMIIT/paper.lnmiit/pull/90/commits/2e74265675d50b9f480ce209f3d93e669a33ab9d

**Comment by yashovardhan** [comment]
there is also no description in the PR, make sure to add a description of the PR from the next time 😄

**Review by divyanshu-rawat — COMMENTED** [review]
thanks for the PR 👍

**Comment by Naman-Garg-06** [comment]
Sir my branch is not updated. How can I do it? I tried to do it using git but it said something about accessing rights.

**Comment by yashovardhan** [comment]
`git pull upstream master`

**Comment by Naman-Garg-06** [comment]
Sir i did the changes u asked for.

**Comment by yashovardhan** [comment]
Good work! 😄 

btw keep in mind, in open source, nobody's a sir, there are no seniors or juniors here, just developers
so to address someone, simply use the GitHub username, like for me @yashovardhanagrawal
😉

**Pull request merged**
