### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by punit-agarwal**
Made some basic changes. Will be adding some more.

### CODE REVIEW

**Comment by sid22** [comment]
Great @punit-agarwal. Could you add more commits to this PR itself? That we can merge this PR when it has substantial changes. Maybe just clean up all the text with relevant one?

**Comment by punit-agarwal** [comment]
@goyal-sidd  sure
Working on it.. :)

**Comment by punit-agarwal** [comment]
https://github.com/punit-agarwal/paper.lnmiit/tree/patch-2

**Review by divyanshu-rawat — COMMENTED** [review]
@goyal-sidd  please review PR carefully before merging and it would be great if the contributor follows contribution guidelines.
https://github.com/Cybros/Lecture-Series-1-HTML-CSS-JS/wiki/Contribution-Guidelines

**Comment by punit-agarwal** [comment]
The merge suggested above needs some changes to be made.
Updating it with a new one.
Sorry for the inconvenience caused.

**Comment by punit-agarwal** [comment]
Please review patch-3

**Review by sid22 — APPROVED** [review]

**Pull request merged**
