### PR TITLE
style.css added | work on cards

### PR DESCRIPTION
**Pull request by swarnim1212**
added style.css and worked on buttons and cards

### CODE REVIEW

**Review by divyanshu-rawat — CHANGES_REQUESTED** [review]
please resolve merge conflicts.

**Review by sid22 — COMMENTED** [review]
@nimbus1212 If you need help in resolving merge conflicts don't hesitate to ask. Otherwise it looks good.

**Comment by swarnim1212** [comment]
i am not able to fetch the upstream...plz help me in resolving conflicts

**Comment by swarnim1212** [comment]
got the solution of fetching issue.

**Review by divyanshu-rawat — APPROVED** [review]

**Review by divyanshu-rawat — CHANGES_REQUESTED** [review]
let's wait for @goyal-sidd  please attach live URL or screenshots of your changes I have approved because merge conflict is resolved.

**Pull request closed without merging**
