### PR TITLE
Fixes

### LINKED ISSUE #59: Major BUG: Paper Download Option Not Working
**I'm submitting a ...**
- [x] bug report

**Current behavior:**
The PHP Script instead of showing the respective papers of every folder is being downloaded. You can check that out at [https://cybros.github.io/paper.lnmiit/](https://cybros.github.io/paper.lnmiit/)

**Expected behavior:**
It should show a page which will let us download the papers.

@amisha2016 you should check this issue here.

### LINKED ISSUE #69: Add a page containing download links for folder contents (Use GitHub APIs)
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**
Script is being downloaded

**Expected behaviour:**
Page must be loaded which contains the downloading links for all the papers uploaded in the specific folder.

**Steps to reproduce:**

1. Get familiar with the way papers are uploaded in the repository, it's quite simple just take a view of the folder structure.
2. Checkout GitHub Rest APIs or GraphQL APIs, there are APIs for almost anything in GitHub.
3. Delete the Current PHP Script, as it is not supported by GitHub Pages.
4. Make an HTML page using the Specific GitHub API and make copies of it in every folder wherever it is required.
5. Send us a PR for it 😄

### PR DESCRIPTION
**Pull request by MohitDeshwal**
Closes #59 and Closes #69 
#### Checklist

- [ ] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

**Changes proposed in this pull request**
- All Files now linked to new download file
- PHP files deleted

**Screenshots (if appropriate)** 

**Link to live demo (if appropriate):** 
https://mohitdeshwal.github.io/
**Closes #**

### CODE REVIEW

**Comment by punit-agarwal** [comment]
Can you provide a working link for all the changes you have made?
Thanks

**Comment by MohitDeshwal** [comment]
https://mohitdeshwal.github.io/

**Comment by MohitDeshwal** [comment]
Fork repo wasn't in sync with this one but as there are no merge conflicts, I think we are good to go.

**Review by yashovardhan — APPROVED** [review]
looks fine to me. Great job! keep contributing :smile:

**Comment by yashovardhan** [comment]
Also in the description, mention to close the issues #59 & #69

**Comment by punit-agarwal** [comment]
Looks good to me too.
Keep contributing. ;)

**Pull request merged**
