### PR TITLE
Added EFE papers.

### LINKED ISSUE #41: Add New Papers !
Add New Papers !

### PR DESCRIPTION
**Pull request by rsinghal26**
Add AP 2017 mid sem paper with solutions in year2/sem1/cse

### CODE REVIEW

**Review by divyanshu-rawat — COMMENTED** [review]
ya wit for other reviewers to review thanks @rsinghal26 👍

**Review by yashovardhan — CHANGES_REQUESTED** [review]
@rsinghal26 Its good that you have started to contribute to this Cybros repository, but please don't take this for granted. Maintain some professionalism while issuing a PR.
First of all, change the name of the PR to indicate what changes you have made.
Your description is fine but kindly remove the "fixes <issue_name>" from there as it will unnecessarily close the issue which is not to be closed.
From next time I hope you would keep these things in mind.

**Review by punit-agarwal — CHANGES_REQUESTED** [review]
These files had already been uploaded by kill gear and his pull request is yet to be merged. So it would be awesome if you upload papers of other subjects.

**Comment by rsinghal26** [comment]
Thank you for ur suggestions. I have done some changes in description according to you.

**Comment by ParthS007** [comment]
@rsinghal26 You have to change the PR title, this time  I have done it for you .From next time please follow the basic PR template and give a valid title to your PR.Keep Contributing :grinning:

**Review by ParthS007 — APPROVED** [review]

**Review by punit-agarwal — APPROVED** [review]

**Review by yashovardhan — APPROVED** [review]

**Review by yashovardhan — CHANGES_REQUESTED** [review]
roll back the AP Mid Sem paper
its already present in the repository

**Review by divyanshu-rawat — COMMENTED** [review]
thanks for the PR 👍

**Review by ParthS007 — APPROVED** [review]

**Comment by yashovardhan** [comment]
Sorry @rsinghal26 EFE papers have also been added in the repository, you can push some other papers if you wish to.. 
update your fork, and find out what papers are missing.
you can find more papers to upload @ http://172.22.2.20:8080/jspui/

I guess you should create a new PR for that now, this PR is getting too messed up.

**Pull request closed without merging**
