### PR TITLE
M-III and EFE Papers added

### PR DESCRIPTION
**Pull request by kalpitmantri**
M-III Quiz1 & Mid-Term papers and EFE Mid-Term paper are added to year2/sem3/cse

### CODE REVIEW

**Comment by punit-agarwal** [comment]
Good job.
It would be awesome if you add M3 files to all the folders in sem3.
Let's wait for others to review.

**Review by yashovardhan — CHANGES_REQUESTED** [review]
@kalpitmantri Thanks for the PR.
I agree with @punit-agarwal 
You may add m3 paper to all the folders.
Do it if you want, no compulsion from our side, this PR is well enough to be merged.
Comment, whenever you think your PR should be merged.

**Review by divyanshu-rawat — COMMENTED** [review]
thanks for the PR 👍

**Review by ParthS007 — APPROVED** [review]

**Review by yashovardhan — APPROVED** [review]
Cool!
I guess we are ready to merge now 😄

**Pull request merged**
