### PR TITLE
Update and rename download.php to download.html

### PR DESCRIPTION
**Pull request by MohitDeshwal**
For the sake of  Github Pages. ;)

Fixes #

#### Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

**Changes proposed in this pull request**
-
-
-

**Screenshots (if appropriate)** 

**Link to live demo (if appropriate):https://mohitdeshwal.github.io/year1/sem1/download.html?var=cse

**Closes #**

### CODE REVIEW

**Comment by MohitDeshwal** [comment]
Please Inform so that I can work further.
i.e 
1) All download.php need to be replaced with this download.html
2) All buttons should point to download.html instead of download.php

**Comment by yashovardhan** [comment]
yup you are right

also provide a working demo from your own GItHub Pages link

It would be quite easier to review

**Review by yashovardhan — APPROVED** [review]

**Comment by yashovardhan** [comment]
That was indeed great work from your side
A live demo would be good too
and also add the download.html to all other folders also, that would be great!

Keep Contributing in Cybros 😄

**Comment by MohitDeshwal** [comment]
Please note Demo Link has few changes from this PR.
-Also, styling is messed.
- I am thinking about keeping a single download.html and point all links to it make the project more Maintainable.

**Review by punit-agarwal — APPROVED** [review]
Good Job.
Keep Contributing to CybrosX

**Pull request merged**
