### PR TITLE
sidebar added & few extra files deleted

### PR DESCRIPTION
**Pull request by yashovardhan**
Added a simple CSS and JS (for toggle menu) based sidebar
you may have a view at 
[https://yashovardhanagrawal.github.io/paper.lnmiit/](https://yashovardhanagrawal.github.io/paper.lnmiit/)

### CODE REVIEW

**Review by divyanshu-rawat — CHANGES_REQUESTED** [review]
thanks for the PR. 
I would like to suggest a change if possible please have a look at this opacity sidebar if you would be able to integrate it then I think it would look nicer https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sidenav_push_opacity

**Comment by yashovardhan** [comment]
nice idea.. will start implementing it now.

**Comment by yashovardhan** [comment]
done changes, I didn't like the colour changing part in the webpage so deleted it.

**Review by divyanshu-rawat — APPROVED** [review]

**Comment by divyanshu-rawat** [comment]
let's wait for Siddharth as well:+1:  
thanks for your patience

**Review by sid22 — APPROVED** [review]
Great work @yashovardhanagrawal

**Pull request merged**
