### PR TITLE
renamed folders

### PR DESCRIPTION
**Pull request by swarnim1212**

### CODE REVIEW

**Review by divyanshu-rawat — COMMENTED** [review]
let's wait for @goyal-sidd @yashovardhanagrawal  @punit-agarwal for review.
thanks for the PR.

**Review by punit-agarwal — APPROVED** [review]

**Comment by yashovardhan** [comment]
@nimbus1212 can you please describe what you have done exactly?
Also can you please provide the link to your working site (Github pages link)
Thanks for PR anyway

**Comment by sid22** [comment]
Great work @nimbus1212. In future do explain the changes briefly .

@yashovardhanagrawal in the meantime, if the changes are not explained in future, you can also fetch a PR locally to your system as a new branch to see changes. For ex: you could pull this PR as 
git fetch origin pull/22/head:pr22 

This will fetch all the changes of this PR over the head of this repo into a new branch "pr22" on your system. Then you can checkout to this branch 'pr22' and see the changes for yourself in the system.

Note: I have assumed that 'origin' remote is the one pointed at the main repo, not your fork.

**Comment by yashovardhan** [comment]
@goyal-sidd thanks for the information that was a new thing I got to know 😄 

for my comment, I just wanted him to be a little specific with his PRs which he was in the next ones. Really nice job @nimbus1212

**Pull request merged**
