### PR TITLE
Option for Download paper in each sem

### LINKED ISSUE #23: Option for downloading paper.
It would be great if we download the paper for the website itself instead of redirecting the client to the GitHub repo. for instance what I mean to say is described below using snapshots.

screenshot from 2017-09-13 21 17 37

screenshot from 2017-09-13 21 17 47

Hope you got the context.

@goyal-sidd  @yashovardhanagrawal  @nimbus1212 @punit-agarwal  any suggestions?

@yashovardhanagrawal  side-bar is missing from other pages. 
here we are missing framework because if we had leveraged a framework than we could have leveraged the power of templates and here are we are violating DRY principle and reinventing the wheel.

### PR DESCRIPTION
**Pull request by amisha2016**
Fixes #23 

#### Checklist

- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)

**Changes proposed in this pull request**
-
-
-

**Screenshots (if appropriate)** 

lnmit

**Link to live demo (if appropriate):** 

[https://amisha.gdy.club/paper.lnmiit](url)

**Closes #**

### CODE REVIEW

**Review by divyanshu-rawat — COMMENTED** [review]
@amisha2016 thanks for the PR.
We would love to merge your PR but before that ley other reviewers review it 👍

**Review by yashovardhan — COMMENTED** [review]
Great work @amisha2016 
This is what I was expecting to be done
your code looks good to me but can you provide a working demo link too?  Like a GitHub Pages Link or something...
it would be much easier for us to review then 😄

**Review by punit-agarwal — APPROVED** [review]
Great work @amisha2016 
A neat and simple code as expected.
Waiting for more PRs from you.
Good job. !!

**Comment by amisha2016** [comment]
@All Thanks for your appreciation.
@yashovardhanagrawal Yeah, you can see working demo over
[https://amisha.gdy.club/paper.lnmiit/](url)

Here is the live demo of downloading paper of sem3 of year 2. Likewise, you can see for all years.
[https://amisha.gdy.club/paper.lnmiit/year2/sem3/download.php?var=cse](url)

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
LGTM
It will be good if you squash commits before pushing them.As you are first timer , I am merging it but keep it mind from now. Keep contributing

**Pull request merged**
